package main

const headerTemplate = `// Code generated by gocodegen({{.Version}})
// THIS FILE HAS BEEN AUTOGENERATED, DO NOT EDIT OR MODIFY !
//
// Generated on {{.DateTime}}
// Generate helper functions for structure "{{.TypeName}}"

`

const builderTemplate = `// New builds and returns new "{{.TypeName}}" entity.
func {{.FuncName}}({{.Params}}) {{.Returned}} {
	{{.Body}}
}

`

const getterTemplate = `// {{.FuncName}} returns the "{{.FieldName}}" parameter.
func (thiz *{{.TypeName}}) {{.FuncName}}() {{.FieldType}} {
	return thiz.{{.FieldName}}
}

`

const setterTemplate = `// {{.FuncName}} sets the "{{.FieldName}}" parameter.
func (thiz *{{.TypeName}}) {{.FuncName}}({{.FieldName}} {{.FieldType}}) {
	thiz.{{.FieldName}} = {{.FieldName}}
}

`

const equalTemplate = `// Equals return true if equlity is satisified otherwise false.
func (thiz *{{.TypeName}}) Equals(other *{{.TypeName}}) bool {
	{{.Body}}
}

`

const structStringerTemplate = `// Return a string value describing the "{{.TypeName}}" entity.
func (thiz *{{.TypeName}}) String() string {
	{{.Body}}
}

`

const structJSONTemplate = `// MarshalJSON returns JSON encoding of "{{.TypeName}}".
func (thiz {{.TypeName}}) MarshalJSON() ([]byte, error) {
	var (
		b   []byte
		err error
	)
	buffer := bytes.Buffer{}
	buffer.WriteByte('{')
	{{$first := true}}{{range $k, $v := .MarshalJSON}}{{if $first}}{{$first = false}}{{else}}buffer.WriteByte(','){{end}}
	buffer.WriteString("\"{{$v.Tag}}\"")
	buffer.WriteByte(':')
	b, err = json.Marshal(thiz.{{$v.Marshal}})
	if err != nil {
		return nil, err
	}
	buffer.Write(b)
	{{end}}
	buffer.WriteByte('}')
	return buffer.Bytes(), nil
}

// UnmarshalJSON sets "{{.TypeName}}" to a copy of data.
func (thiz *{{.TypeName}}) UnmarshalJSON(data []byte) error {
	var err error

	tmp := struct { {{range $k, $v := .MarshalJSON}}{{if ne $v.Type "time.Time" }}
		{{$k}} {{$v.Type}} ` + "`" + `json:"{{$v.Tag}}"` + "`" + `{{end}}{{end}}
	}{}
	err = json.Unmarshal(data, &tmp)
	if err != nil {
		return err
	}
	{{range $k, $v := .MarshalJSON}}{{if ne $v.Type "time.Time" }}{{$v.Unmarshal}}
	{{end}}{{end}}
	return nil
}

`

const enumStringerTemplate = `// String returns a string describing the "{{.TypeName}}" value.
func (e {{.TypeName}}) String() string {
	switch e {
	{{range .Constants -}}
	case {{.}}:
		return "{{.}}"
	{{end -}}
	default:
		return "Undefined"
	}
}

// FromString converts a string into its corresponding "{{.TypeName}}" value.
func (e *{{.TypeName}}) FromString(s string) {
	switch s {
	{{range .Constants -}}
	case "{{.}}":
		*e = {{.}}
	{{end -}}
	default:
		*e = {{.Default}}
	}
}

`

const enumJSONTemplate = `// MarshalJSON returns the JSON encoding of "{{.TypeName}}".
func (e {{.TypeName}}) MarshalJSON() ([]byte, error) {
	str := e.String()
	b, err := json.Marshal(&str)
	if err != nil {
		return b, fmt.Errorf("failed to marshal JSON: %v", err)
	}
	return b, err
}

// UnmarshalJSON sets "{{.TypeName}}" to a copy of data.
func (e *{{.TypeName}}) UnmarshalJSON(data []byte) error {
	str := ""
	if err := json.Unmarshal(data, &str); err != nil {
		return fmt.Errorf("failed to unmarshal JSON input: %v", err)
	}
	e.FromString(str)
	return nil
}

`
