// Code generated by gocodegen(1.0.0)
// THIS FILE HAS BEEN AUTOGENERATED, DO NOT EDIT OR MODIFY !
//
// Generated on Fri, 31 Jan 2025 19:03:22
// Generate helper functions for structure "Test"

package main

import (
	"bytes"
	"encoding/json"
	"fmt"
	"time"
)

// String returns a string describing the "Animal" value.
func (e Animal) String() string {
	switch e {
	case Dog:
		return "Dog"
	case Cat:
		return "Cat"
	default:
		return "Undefined"
	}
}

// FromString converts a string into its corresponding "Animal" value.
func (e *Animal) FromString(s string) {
	switch s {
	case "Dog":
		*e = Dog
	case "Cat":
		*e = Cat
	default:
		*e = Dog
	}
}

// MarshalJSON returns the JSON encoding of "Animal".
func (e Animal) MarshalJSON() ([]byte, error) {
	str := e.String()
	b, err := json.Marshal(&str)
	if err != nil {
		return b, fmt.Errorf("failed to marshal JSON: %v", err)
	}
	return b, err
}

// UnmarshalJSON sets "Animal" to a copy of data.
func (e *Animal) UnmarshalJSON(data []byte) error {
	str := ""
	if err := json.Unmarshal(data, &str); err != nil {
		return fmt.Errorf("failed to unmarshal JSON input: %v", err)
	}
	e.FromString(str)
	return nil
}

// New builds and returns new "Test" entity.
func NewTest(Name string, Descr *string) *Test {
	return &Test{
		Name: Name,
		Descr: Descr,
	}
}

// Return a string value describing the "Test" entity.
func (thiz *Test) String() string {
	return fmt.Sprintf("Test{%v,%v,%v}",
		thiz.Date.UTC().Format("2006/01/02 15:04:05"),
		thiz.Name,
		thiz.Descr)
}

// Equals return true if equlity is satisified otherwise false.
func (thiz *Test) Equals(other *Test) bool {
	return thiz.Date.Equal(other.Date) &&
		thiz.Name == other.Name &&
		thiz.ID == other.ID
}

// SetDate sets the "Date" parameter.
func (thiz *Test) SetDate(Date time.Time) {
	thiz.Date = Date
}

// GetDate returns the "Date" parameter.
func (thiz *Test) GetDate() time.Time {
	return thiz.Date
}

// SetName sets the "Name" parameter.
func (thiz *Test) SetName(Name string) {
	thiz.Name = Name
}

// GetName returns the "Name" parameter.
func (thiz *Test) GetName() string {
	return thiz.Name
}

// SetDescr sets the "Descr" parameter.
func (thiz *Test) SetDescr(Descr *string) {
	thiz.Descr = Descr
}

// GetDescr returns the "Descr" parameter.
func (thiz *Test) GetDescr() *string {
	return thiz.Descr
}

// GetID returns the "ID" parameter.
func (thiz *Test) GetID() int {
	return thiz.ID
}

// SetArray sets the "array" parameter.
func (thiz *Test) SetArray(array []string) {
	thiz.array = array
}

// GetArray returns the "array" parameter.
func (thiz *Test) GetArray() []string {
	return thiz.array
}

// SetMmap sets the "mmap" parameter.
func (thiz *Test) SetMmap(mmap map[string]float32) {
	thiz.mmap = mmap
}

// GetMmap returns the "mmap" parameter.
func (thiz *Test) GetMmap() map[string]float32 {
	return thiz.mmap
}

// SetChannel sets the "channel" parameter.
func (thiz *Test) SetChannel(channel chan int) {
	thiz.channel = channel
}

// GetChannel returns the "channel" parameter.
func (thiz *Test) GetChannel() chan int {
	return thiz.channel
}

// SetFunction sets the "function" parameter.
func (thiz *Test) SetFunction(function func(int, string) float64) {
	thiz.function = function
}

// GetFunction returns the "function" parameter.
func (thiz *Test) GetFunction() func(int, string) float64 {
	return thiz.function
}

// SetIt sets the "it" parameter.
func (thiz *Test) SetIt(it interface{}) {
	thiz.it = it
}

// GetIt returns the "it" parameter.
func (thiz *Test) GetIt() interface{} {
	return thiz.it
}

// SetSt sets the "st" parameter.
func (thiz *Test) SetSt(st struct {
	a string
	b int
}) {
	thiz.st = st
}

// GetSt returns the "st" parameter.
func (thiz *Test) GetSt() struct {
	a string
	b int
} {
	return thiz.st
}

// MarshalJSON returns JSON encoding of "Test".
func (thiz Test) MarshalJSON() ([]byte, error) {
	var (
		b   []byte
		err error
	)
	buffer := bytes.Buffer{}
	buffer.WriteByte('{')
	
	buffer.WriteString("\"date\"")
	buffer.WriteByte(':')
	b, err = json.Marshal(thiz.Date)
	if err != nil {
		return nil, err
	}
	buffer.Write(b)
	buffer.WriteByte(',')
	buffer.WriteString("\"dateEpoch\"")
	buffer.WriteByte(':')
	b, err = json.Marshal(thiz.Date.Unix())
	if err != nil {
		return nil, err
	}
	buffer.Write(b)
	buffer.WriteByte(',')
	buffer.WriteString("\"descr\"")
	buffer.WriteByte(':')
	b, err = json.Marshal(thiz.Descr)
	if err != nil {
		return nil, err
	}
	buffer.Write(b)
	buffer.WriteByte(',')
	buffer.WriteString("\"id\"")
	buffer.WriteByte(':')
	b, err = json.Marshal(thiz.ID)
	if err != nil {
		return nil, err
	}
	buffer.Write(b)
	buffer.WriteByte(',')
	buffer.WriteString("\"name\"")
	buffer.WriteByte(':')
	b, err = json.Marshal(thiz.Name)
	if err != nil {
		return nil, err
	}
	buffer.Write(b)
	
	buffer.WriteByte('}')
	return buffer.Bytes(), nil
}

// UnmarshalJSON sets "Test" to a copy of data.
func (thiz *Test) UnmarshalJSON(data []byte) error {
	var err error

	tmp := struct { 
		DateEpoch int64 `json:"dateEpoch"`
		Descr *string `json:"descr"`
		ID int `json:"id"`
		Name string `json:"name"`
	}{}
	err = json.Unmarshal(data, &tmp)
	if err != nil {
		return err
	}
	thiz.Date = time.Unix(tmp.DateEpoch, 0).UTC()
	thiz.Descr = tmp.Descr
	thiz.ID = tmp.ID
	thiz.Name = tmp.Name
	
	return nil
}

